AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-yard
  - ./rubocop/require_yard_doc.rb

YARD/RequireDocumentation:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 8
